FROM python:3-slim-buster

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY app app
COPY config config
COPY migrations migrations
COPY entrypoint.sh entrypoint.sh
COPY run.py run.py

CMD "./entrypoint.sh"
