# Generated by Django 4.1.5 on 2023-02-10 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id_backup', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Código del backup', max_length=64)),
                ('description', models.TextField(help_text='Descripción asociada al backup', max_length=300, null=True)),
                ('source_dir', models.CharField(max_length=256)),
                ('destination_dir', models.CharField(max_length=256)),
                ('user', models.CharField(help_text='Usuario del servicio de almacenamiento', max_length=64)),
                ('password', models.CharField(help_text='Contraseña del servicio de almacenamiento', max_length=64)),
                ('n_backups_max', models.IntegerField(default=10, help_text='Nº de backups disponibles')),
                ('sw_sensor_mqtt', models.BooleanField(default=False, help_text='Avisar por MQTT de cambios')),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de alta del backup', verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='StorageService',
            fields=[
                ('id_storage_service', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código del servicio de almacenamiento', max_length=8)),
                ('name', models.CharField(help_text='Nombre del servicio de almacenamiento', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id_backup_history', models.AutoField(primary_key=True, serialize=False)),
                ('backup_name', models.CharField(help_text='Nombre del fichero de backup', max_length=64)),
                ('backup_size', models.IntegerField(default=0, help_text='Tamaño del backup')),
                ('status', models.CharField(default='PDTE', help_text='Estado del backup', max_length=8)),
                ('duration', models.FloatField(default=0, help_text='Duración de la creación del backup')),
                ('audit_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Indica la fecha de creación del backup', verbose_name='Fecha de creación')),
                ('id_backup_fk', models.ForeignKey(help_text='Backup asociado', on_delete=django.db.models.deletion.CASCADE, to='backups.backup')),
            ],
        ),
        migrations.AddField(
            model_name='backup',
            name='id_storage_service_fK',
            field=models.ForeignKey(help_text='Código del servicio de almacenamiento', on_delete=django.db.models.deletion.CASCADE, to='backups.storageservice'),
        ),
    ]
