# Generated by Django 4.1.6 on 2023-02-10 16:23

from django.db import migrations

from backups.models import StorageService


def add_storage_service(apps, schema_editor):
    StorageService(code='MEGA', name='MEGA').save()


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_storage_service),
    ]
