name: Docker image CI

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: omikel8
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (dev)
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: omikel8/taix_backups:dev
          platforms: linux/amd64,linux/arm64
